### ISSUE TITLE
공부 방식에 대한 질문

### ISSUE THREAD

**Issue by JSY8869** [JSY8869/KGU.DLstudy#2]
# 공부 방식?
- [ ] 1. notion에 내가 한 것처럼 정리하고 일주일에 한번 서로 발표한다.
- [ ] 2. notion에 내가 한 것처럼 정리하고 모르겠는 것만 서로 질문한다.
- [ ] 3. notion에 내가 한 것처럼 정리하고 나한테 강의를 듣는다.
- [ ] 4. 내가 정리해논 것을 보고 모르겠는 부분을 나한테 질문한다.
- [x] 5. 나한테 강의를 듣는다.
- [ ] 6. 기타 의견

**Comment by park-sohyeon** [comment]
완전 처음이라 우선 강의를 들으면서 이해해야 될 것 같아요, 강의 듣고 제가 notion에 정리하겠습니다

**Comment by JSY8869** [comment]
그럼 시간 정해서 알려줘~ 나는 이번주는 언제든 크게 상관 없을듯

**Comment by park-sohyeon** [comment]
화요일 4시로 하겠습니당
